### ISSUE TITLE
Auth window opens, but no login happens

### ISSUE THREAD

**Issue by jhalexand** [DevMatGod/Glogin#7]
I've installed Glogin in my test site and I'm trying to get it working.  So far as I can tell, I've set up OAuth properly and I've added the module to a login landing page. I can click on the login button, I get a pop-up asking me to choose an account.  I choose one that is within the domain I set up in the plugin (and for which I've configured OAuth), the login window thinks for a few seconds (the google loading indicators scrolls across the top of the popup), then the popup closes and my original page is still sitting there, having not logged in. I can't find anything in the documentation to suggest what I'm missing.  Any tips? It'd be great to have GSuite integration in our site.  Thanks!

**Comment by jhalexand** [comment]
A little more info.  The behavior above is in Safari. In firefox, I do get a page redirect, but I get the output:

Error: Call to undefined method Joomla\CMS\Component\Exception\MissingComponentException::get(): Component not found.

And in my error log, I see

```
2020-08-06T05:09:23+00:00	CRITICAL 72.93.226.115	error	Uncaught \Throwable of type Joomla\CMS\Component\Exception\MissingComponentException thrown. Stack trace: #0 /home/...../libraries/src/Application/SiteApplication.php(194): Joomla\CMS\Component\ComponentHelper::renderComponent('com_login')
#1 /home/...../libraries/src/Application/SiteApplication.php(233): Joomla\CMS\Application\SiteApplication->dispatch()
#2 /home/...../libraries/src/Application/CMSApplication.php(196): Joomla\CMS\Application\SiteApplication->doExecute()
#3 /home/...../index.php(49): Joomla\CMS\Application\CMSApplication->execute()
#4 {main}

```
